---
- name: Install Classact
  hosts: windows
  strategy: free
  tasks:
    - name: Ensure destination directory exists
      ansible.windows.win_file:
        path: D:\bahasa
        state: directory

    - name: Copy files
      ansible.windows.win_copy:
        src: "{{ item }}"
        dest: D:\bahasa\
      loop: 
        - AESEncDecInstallerVer3.exe
        - Classact Lugha 2024 Installer.exe
        - License Key.txt
        - Game.7z.001
        - Game.7z.002
        - Game.7z.003
        - Game.7z.004
        - Game.7z.005
        - Game.7z.006
        - Game.7z.007
        - Game.7z.008
        - Game.7z.009
        - Game.7z.010
        - Game.7z.011
        - Game.7z.012
        - Game.7z.013
        - Game.7z.014
        - Game.7z.015
        - Game.7z.016
        - Game.7z.017
        - Game.7z.018
        - Game.7z.019
        - Game.7z.020

    - name: Install Classact Lugha 2024 to custom folder
      ansible.windows.win_shell: |
        Start-Process -FilePath "D:\\bahasa\\Classact Lugha 2024 Installer.exe" `
          -ArgumentList "/silent /allusers /DIR=D:\\bahasa\\ClassactLugha2024" `
          -NoNewWindow

    - name: Ensure Game folder exists in the custom folder
      ansible.windows.win_file:
        path: D:\bahasa\ClassactLugha2024\MainApp\NewBuild\Game
        state: directory
    
    - name: Install PSCX module for all users
      win_shell: |
        Install-Module -Name Pscx -RequiredVersion 3.3.2 -Force -AllowClobber -Scope CurrentUser

    - name: Install Pscx module for all users
      win_shell: |
        Get-Module -ListAvailable PSCX

    - name: Unzip .7z
      community.windows.win_unzip:
        src: D:\bahasa\Game.7z.001
        dest: D:\bahasa\ClassactLugha2024\MainApp\NewBuild
